apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results-service
  template:
    metadata:
      labels:
        app: results-service
    spec:
      containers:
        - name: results-service
          image: chkhonty9/biolab-result:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              port: 3000
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: DISCOVERY_SERVICE_HOST
              value: discovery-service
            - name: CONFIG_SERVICE_URL
              value: http://config-service:9999

---
---
apiVersion: v1
kind: Service
metadata:
  name: results-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030
  selector:
    app: results-service