apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-deploy
  labels:
    name: results-deploy
    app: bioLab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: results-pod
      app: bioLab-app
  template:
    metadata:
      name: results-pod
      labels:
        name: results-pod
        app: bioLab-app
    spec:
      containers:
        - name: results-service
          image: chkhonty9/biolab-result:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              port: 3000
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: DISCOVERY_SERVICE_HOST
              value: discovery-service
            - name: CONFIG_SERVICE_URL
              value: http://config-service:9999

---
---
apiVersion: v1
kind: Service
metadata:
  name: results-service
  labels:
    name: results-service
    app: bioLab-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030
  selector:
    name: results-pod
    app: bioLab-app