apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deploy
  labels:
    name: config-deploy
    app: bioLab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: config-pod
      app: bioLab-app
  template:
    metadata:
      name: config-pod
      labels:
        name: config-pod
        app: bioLab-app
    spec:
      containers:
        - name: config-service
          image: chkhonty9/biolab-config:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
          readinessProbe:
            httpGet:
              port: 9999
              path: /actuator/health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://discovery-service:8761"
---
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    name: config-service
    app: bioLab-app
spec:
  type: NodePort
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30099
  selector:
    name: config-pod
    app: bioLab-app