apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: chkhonty9/biolab-config:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
          readinessProbe:
            httpGet:
              port: 9999
              path: /actuator/health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka

---
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: LoadBalancer
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30099
  selector:
    app: config-service