spring:
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: lb://PROJECT-SERVICE  # This will use Eureka to discover the service
          predicates:
            - Path=/PROJECT-SERVICE/**  # All paths matching this will be forwarded to project-service
        - id: results-service
          uri: lb://RESULTS-SERVICE
          predicates:
            - Path=/RESULTS-SERVICE/**
        - id: materiels-service
          uri: lb://MATERIELS-SERVICE
          predicates:
            - Path=/MATERIELS-SERVICE/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/USER-SERVICE/**