spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/user-service/**
        - id: results-service
          uri: http://results-service:3000
          predicates:
            - Path=/results-service/**
        - id: materiels-service
          uri: http://materiels-service:8082
          predicates:
            - Path=/materiels-service/**
        - id: project-service
          uri: http://project-service:5000
          predicates:
            - Path=/project-service/**
