spring:
  cloud:
    gateway:
      routes:
        - id: config-service
          uri: lb://config-service
          predicates:
            - Path=/config/**  # Adjust this path as needed

        - id: materiels-service
          uri: lb://materiels-service
          predicates:
            - Path=/materiels/**

        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**

        - id: results-service
          uri: lb://results-service
          predicates:
            - Path=/results/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**