- name: Deploy microservice dans kubernetes
  hosts: my_server
  gather_facts: no
  tasks:
    - name: create folder
      win_file:
        path: "/home/nouhaila/deploy"
        state: directory

    - name: Copy file discovery-deploy.yaml
      copy:
        src: "{{ playbook_dir }}/discovery-deploy.yaml"
        dest: "/home/nouhaila/deploy/discovery-deploy.yaml"

    - name: deployment kubernetes
      win_command: "kubectl apply -f /home/nouhaila/deploy/discovery-deploy.yaml"

    - name: Validation deployment
      win_command: "kubectl get pods"
      register: pod_status

    - name: Display pod status
      debug:
        msg: "Pods Status: {{ pod_status.stdout }}"