apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deploy
  labels:
    name: project-deploy
    app: bioLab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: project-pod
      app: bioLab-app
  template:
    metadata:
      name: project-pod
      labels:
        name: project-pod
        app: bioLab-app
    spec:
      containers:
        - name: project-service
          image: chkhonty9/biolab-project:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              port: 5000
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka
            - name: CONFIG_SERVICE_URL
              value: http://config-service.default.svc.cluster.local:9999
---
---
apiVersion: v1
kind: Service
metadata:
  name: project-service
  labels:
    name: project-service
    app: bioLab-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050
  selector:
    name: project-pod
    app: bioLab-app