apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: chkhonty9/biolab-user:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              port: 8082
              path: /actuator/health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:8761/eureka
            - name: CONFIG_SERVICE_URL
              value: http://config-service:9999
---
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  selector:
    app: user-service