apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  labels:
    name: user-deploy
    app: bioLab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-pod
      app: bioLab-app
  template:
    metadata:
      name: user-pod
      labels:
        name: user-pod
        app: bioLab-app
    spec:
      containers:
        - name: user-service
          image: chkhonty9/biolab-user:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              port: 8082
              path: /actuator/health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:8761/eureka
            - name: CONFIG_SERVICE_URL
              value: http://config-service:9999
---
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    name: user-service
    app: bioLab-app
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  selector:
    name: user-pod
    app: bioLab-app