apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    name: gateway-deploy
    app: bioLab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gateway-pod
      app: bioLab-app
  template:
    metadata:
      name: gateway-pod
      labels:
        name: gateway-pod
        app: bioLab-app
    spec:
      containers:
        - name: gateway-service
          image: chkhonty9/biolab-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              port: 8888
              path: /actuator/health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:8761/eureka
            - name: CONFIG_SERVICE_URL
              value: http://config-service:9999
---
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    name: gateway-service
    app: bioLab-app
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088
  selector:
    name: gateway-pod
    app: bioLab-app