apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: gateway-service-role
rules:
  - apiGroups: [""]
    resources: ["endpoints", "services"]
    verbs: ["list", "get"]

---
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-service-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: gateway-service-role
  apiGroup: rbac.authorization.k8s.io
