apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: chkhonty9/biolab-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              port: 8888
              path: /actuator/health
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:8761/eureka
            - name: CONFIG_SERVICE_URL
              value: http://config-service:9999
---
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088
  selector:
    app: gateway-service