apiVersion: apps/v1
kind: Deployment
metadata:
  name: materiels-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: materiels-service
  template:
    metadata:
      labels:
        app: materiels-service
    spec:
      containers:
        - name: materiels-service
          image: chkhonty9/biolab-materiels:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              port: 8081
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service:8761/eureka
            - name: CONFIG_SERVICE_URL
              value: http://config-service:9999
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8081"
---
---
apiVersion: v1
kind: Service
metadata:
  name: materiels-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: materiels-service